### PR TITLE
Add field-specific search options.

### PR DESCRIPTION
**Pull request by hivehand**
If passed the '-a' ("align") flag, `brew desc` right-aligns the names
to the end of the widest one, making all descriptions begin in the
same column.

(Background/rationale: I tend to pipe the output of a `brew update` into `brew desc` to see what interesting new formulae might be out there. Skimming the results of a bulk-desc is easier when every description starts in the same column.)

### CODE REVIEW

**Comment by hivehand** [comment]
...aaand I just realized that my tweak does nothing to format the results of a `brew desc -s`. Let me see if I can fix that.

**Comment by hivehand** [comment]
I might… have gone just a bit off the deep end. Once I started diving into the `--search` side, I realized that it would avoid an abundance of code duplication if desc’s operation was split into two discrete steps: getting an array of names, whether by search or explicitly provided list, and then presenting the descriptions corresponding to those names.

Adding a new flag prompted me to use [OptionParser](http://ruby-doc.org/stdlib-2.2.2/libdoc/optparse/rdoc/OptionParser.html) to process the options and then pull them out of `ARGV`, so that flags wouldn’t be mistaken for search terms.

Once I’d done that, I figured I might as well use OptionParser to add flags that can limit the search to either formula names or descriptions.

Let me know if all of this is useful, needs revision, or is just flat-out insane.

**Comment by telemachus** [comment]
Thank you for your interest in `brew desc` and for all of this work.

I have to admit that my first thought is that this adds complexity to something that I would prefer to keep as simple as possible. My own inclination would be to leave `brew desc` as is and suggest you pipe it into a filter to align it.

That said, I don't want to rule it out either if it's of interest to a lot of users. I'm going to leave this open for now while I think about it further. For the moment, I encourage you to use your own fork to see how it works in practice. Thanks.

**Comment by hivehand** [comment]
Thanks for the feedback. Regarding the column-alignment logic, your point about making it the work of a post-filter is entirely valid; I’d be happy to remove that code.

However, other code came along for the ride, in particular the ability to limit search matches to just names or just descriptions. I’ve wanted that in the past, and have already made productive use of it.

There’s also the consolidation of the presentation logic, regardless of source; while that doesn’t have much effect on the user experience, I’d argue that it does make maintenance of the code easier.

Thanks for your consideration. Cheers!

**Comment by telemachus** [comment]
> However, other code came along for the ride, in particular the ability to limit search matches to just names or just descriptions. I’ve wanted that in the past, and have already made productive use of it.
>
> There’s also the consolidation of the presentation logic, regardless of source; while that doesn’t have much effect on the user experience, I’d argue that it does make maintenance of the code easier.

These are both good point. I agree that limiting searches one way or the other would likely be useful for many users. And it's hard to argue with easier maintenance.

Can you please make a pull request with just those changes for me to look at? (Don't worry at all about a clean history. I can squash it all down before merging anyhow.)

Thanks!

**Comment by hivehand** [comment]
Done. (I’ve kept the use of OptionParser. I think that’s less error-prone than manipulating ARGV directly by hardcoded index, especially as you add more options. I hope that’s OK with you.)

The one caveat in my version, IMHO, is that a search generates a new hash that’s a subset of `description`… and then immediately throws away the values, keeping only the keys. This does let us use the same loop to output the results for a search or an explicit list of formula names, and so seems worth it to me, but YMMV.

Let me know if you have any further requests or suggestions, and whether I should close this pull request and create a new one.

**Comment by telemachus** [comment]
> Done.

Thank you.

> Let me know if you have any further requests or suggestions, and whether I should close this pull request and create a new one.

It's fine to keep it here. I'm going to check this out locally and test run it for a bit while I look over the code. I probably won't merge it right away, so I want to let you know I'm not ignoring it either. I just want to be careful before making any final decisions.

**Comment by telemachus** [comment]
One immediate question as a user: Do you think it would make sense to have `-n` or `-d` accept a term as an argument directly? That is, rather than having to run `brew desc -s term -n`, the user could just run `brew desc -n term`. My thought is that a user would never use `-n` or `-d` *unless* they also have a term. So it would cut down on the complexity of the command from the user's point of view.

Discuss!

**Comment by hivehand** [comment]
Hmm. That’s a good point. My initial implementation was a function of my personal pattern:

1. Issue `brew desc -s <pattern>`, e.g. `brew desc -s git`.
2. Say “Whoa, let’s narrow that down a bit.”
3. Go back one step in history, and tack `-n` onto the end of the command I just issued.

This spares my lazy hands from having to maneuver the cursor back into my command and change the `-s` into `-n`. But you’re absolutely right that users who know from the outset that they want to perform a limited search should, ideally, be spared having to enter two flags when one could do.

I think that I have an idea for reconciling the two approaches. I will fiddle with it a bit and get back to you.

**Comment by hivehand** [comment]
I’ve revised the option-processing and search logic to give you the perfectly reasonable direct option you suggested, while still indulging my lazy hands. As a bonus, some new search abilities came along for the ride. I’ve updated the README to describe the new behaviors, but basically:

`brew desc -s <term>` works as before.
`brew desc -n <term>` works as you suggested.
`brew desc -s <term> -n` works as before, with `-n` essentially “drafting” the argument to `-s`.

The new abilities come in the form of combinations: if you really want to, you can now search for formulae that have one term *somewhere*, and another term specifically in the name (`brew desc -s <term1> -n <term2>`), one term specifically in the name and another in the description (`brew desc -n <term2> -d <term3>`), or even one term anywhere, one term in the name, and one term in the description (`brew desc -s <term1> -n <term2> -d <term3>`).

This all makes sense to me — with simple searches simple, and trickier ones possible — but I’m obviously biased. I’d like your opinion on whether the various possible combinations are helpful, or just confusing.

**Comment by telemachus** [comment]
@hivehand I like the basic idea, but I have to admit I think this version is a lot more complicated than I'd like.

Can I ask you to consider the [search-options branch](https://github.com/telemachus/homebrew-desc/tree/search-options) that I just made? It's probably crude, but I wonder what you think of a more simple (maybe too simplistic) version.

**Comment by hivehand** [comment]
I’m not entirely sure if you mean complicated from the user’s perspective, or the code perspective. From the user’s perspective, the `-s`, `-n`, and `-d` flags, when used by themselves, do exactly the same thing in either case. The user doesn’t need to know or care about the possible combinations out of the gate, but can fall back upon them if further filtration is desired.

As for code complexity, if my line counts are correct, what I’m proposing consists of:

- 9 lines of argument processing, starting at 3137
- 12 of argument post-processing (the “draft”), starting at 3163
- 7 lines of searching, starting at 3184

For a total of 28 search-related lines.

The just-one-type implementation is simpler in the middle, but more involved at the ends:

- 13 lines of argument processing, starting at 3158
- 5 lines of argument post-processing to enforce the “just one search” rule, starting at 3178
- 14 lines of searching, starting at 3184

For a total of 32 search-related lines.

(That’s discounting comments and blank lines in both cases, of course.)

I’m therefore not sure if I entirely understand the complexity concern. That having been said, I will take no offense if you decide that what I’m proposing isn’t to your liking. I can always just pick up my marbles and go play in my own fork. :-)

**Comment by telemachus** [comment]
Thanks for the feedback. I did mean from the user's point of view. Although I understand that a user *could* simply employ the `-s`, `-n`, `-d` flags in the simpler fashion, the amount of possible options available in your version worries me. Even to describe it all clearly strikes me as worryingly complex. I'm imagining a user new to `brew desc` reading the help page. If it were me, I would feel overwhelmed initially, and it might turn me away. (I may be an extreme, but I really prefer simple tools.)

That said, one other thought is that we could divide the help screen almost in half, the first portion laying out the "simple" version, and then a later section detailing the more complex available choices. I'm not sure if I love that, but I may try to write that version of the help to see if it makes things better.

**Comment by hivehand** [comment]
Ah. I see your point. Initially describing only the simple version makes sense to me. The “crazy variations” section could be moved to an appendix or something. Or left out entirely, making the combination-based searches a sort of easter egg. The one catch would be the descriptions for the `-n` and `-d` flags generated automatically by OptionParser, which describe the flags’ arguments as optional.

But to repeat what I said earlier, I’ll take no offense if you just decide to go with the simpler version on your branch. Part of me is starting to worry that I’m taking up too much of your time, and being a distraction.

**Comment by telemachus** [comment]
> Part of me is starting to worry that I’m taking up too much of your time, and being a distraction.

You definitely were not. The feedback was good since it was a relatively large change. I hope I didn't waste your time too much going back and forth.

In the end, I decided to go with my version for now. I added you to the contributors list (I'm assuming you won't mind!) since even though I didn't merge your PR, you gave me the idea and the impetus for this change.

Interestingly, all of this may soon be moot. There's a [pending PR that will merge `brew desc` into `brew` itself](https://github.com/Homebrew/homebrew/pull/39911). Once that happens, I will likely retire this external command, though maybe not. (It depends on how much of the functionality of `brew desc` they accept.)

Again, thank you for your patience and your contribution.

**Comment by hivehand** [comment]
I’m glad to hear that I wasn’t being a hassle, and grateful for being added to the contributors list!

The back and forth was interesting, so I don’t mind it in the least.

Cheers!

**Pull request closed without merging**
