### PR TITLE
Added mupdf-tools desc

### PR DESCRIPTION
**Pull request by alexandregz**

### CODE REVIEW

**Comment by alexandregz** [comment]
Added git-fixup too :smile:

**Comment by alexandregz** [comment]
Deleted adobe-air-sdk and fishfish

**Comment by alexandregz** [comment]
You're welcome :+1:

**Comment by telemachus** [comment]
Merged. Thanks!

**Comment by telemachus** [comment]
One note for future pull requests: It's easier for me to squash into one commit if you keep it as one pull request and just keep adding to it, rather than making multiple branches. Not a huge deal, but FYI.

**Comment by alexandregz** [comment]
I wil make this way in future commits, sure, sorry.

**Comment by telemachus** [comment]
Not a huge deal at all. Just something I noticed when working with these two pull requests versus the last.

More importantly though: Thank you for all your recent contributions to brew-desc.

**Pull request closed without merging**
