### PR TITLE
Edit description phrasing in brew-desc.rb

### PR DESCRIPTION
**Pull request by Zearin**
Edited phrasing of descriptions to make them more “glanceable”.  

I did this by fixing some inconsistencies.  In doing so, I also introduced some inconsistencies of my own—but IMO they are much less…I suppose “disruptive” is the word?  

I realize that’s an odd word to use, since we’re talking about short, one-line descriptions.  However, since this formula tends be used by people who are in “exploration mode” on the command line, I think it’s important.  

In particular, I’ll emphasize these changes:

- **Capitalization**.  If you’re talking about the protocol, it’s “SSH”.  If you’re talking about the program by its name, it’s “ssh”.
- **Leading/trailing spaces**.  Fixed a few leading and trailing spaces sprinkled throughout the descriptions.
- **Brevity.** A huge number of descriptions lead with “Tool for…” or “Utility to…”.  If I could delete this and find a concise rephrasing, I did. 
    - I did *not* do this when…:
        - A formula installed “tools” or “utilities”—plural.  In the former case, a single “tool” or “utility” usually installs a program with the same name as the formula itself.  On the other hand, when a single `brew install «formula»` results in multiple new commands, I left the description intact to explicitly communicate this.
        - I couldn’t come up with a suitable rewrite.
- **It’s “OS X”!**  Not “OSX”. Not “Mac OS X” (not for many years, anyway!).
- **Oxford comma.** This is a matter of personal preference, but I prefer the Oxford comma. It more closely resembles how people would read the text aloud—and (for me, at least) seems to read a little easier.  
- **Written in «language»**.  Where possible, I moved this from the beginning or middle of a description to the end, and put it after a semi-colon.  
    - __*Rationale:*__  Sometimes users *do* care what a particular tool is written in, so it’s information worth including.  But most of the time, people who read the description are wondering what a piece of software **is**, not what it’s written in.  Therefore, I put it at the end, so that *the first thing a person reads* is *what the software is*.
    - I did **not** do this when the description read, e.g., “A C++ library for performing…”.  That’s because it’s ambiguous whether this means the library is written in C++, or whether it’s merely intended for other C++ code.  (In other words, it could be “A C++ library” that’s written in C.  In this case, it would be inaccurate to say “written in C++” for the description.)

In general, I also tweaked phrasing here and there, if I thought it would “read easier”.  

----

I think that covers it.  Let me know if missed anything.

Thanks!

### CODE REVIEW

**Comment by telemachus** [comment]
Initial response: Thank you! This is the kind of thing I've meant to do for years but simply haven't carved out enough time. I'm on vacation, so being a little slow about PRs. But I will certainly get to this sometime this week.

**Comment by telemachus** [comment]
Ok, I pulled this, but I had to edit it a ton. Some notes for future work:

1. Please don't overpunctuate. Two things jumped out at me:
                + Descriptions like this do not need a comma before *and*: "Scan log files, and ban IPs showing malicious signs"
                + The descriptions are too short ever to need semicolons. There's almost always an easier way.
1. If something actually is a C or C++ library, it should say that right at the start of the description (that is essential information for a potential user).
1. However, if something is just a tool written in C, C++, Java, Python, Go, Ruby or whatever, then I agree with you that it's not essential. But I went even further than you: I removed nearly all of those. I say "nearly" because I'm sure I missed some or was not 100% consistent. C'est la vie.
1. I finally decided to make a rule: in this file, everything is now *command-line*, not *command line* or *commandline*. Whew.

Thanks so much for the overall cleanups though!

**Comment by Zearin** [comment]
Got it!  Thanks for sharing your rationale.  

I will miss the ability to see what some projects are written in.  While it’s definitely second-class info, sometimes it’s still something I’d try to search for.  

Why? Maybe I want to customize something and I don’t know C, so I want to search for something in Python; or maybe I want to look at the source code to learn how to do something; or maybe I’m looking for something written in Ruby so that it can talk to some code that I’m writing on my own machine.  

I respect your decision to remove it, and I do concede the secondary nature of that information—I just wanted to communicate that, secondary or not, there’s still some value there.  Still, I’m glad I was able to contribute *some* of my edits.  :)   

In any case, if I make another Pull Request like this in the future and you’re only on board with *some* of my changes, you can just ask me to adjust my PR and I’ll make the changes.  Might save you a little work.  ;)

Thanks!

**Comment by telemachus** [comment]
> I will miss the ability to see what some projects are written in. While it’s definitely second-class info, sometimes it’s still something I’d try to search for.
>
> Why? Maybe I want to customize something and I don’t know C, so I want to search for something in Python; or maybe I want to look at the source code to learn how to do something; or maybe I’m looking for something written in Ruby so that it can talk to some code that I’m writing on my own machine.

Honestly, I agree. I may add them all back soon. I don't know. I'm having editor's remorse now! In any case, I'll keep your thoughts in mind.

**Pull request merged**
