### PR TITLE
Update brew-desc.rb

### PR DESCRIPTION
**Pull request by Yann-R**
I improved some descriptions for a few formulae I use on my system, according to their homepages or manpages.

### CODE REVIEW

**Comment by Yann-R** [comment]
I really appreciate the purpose of `brew desc`. Thank you guy!
I just tried to edit some descriptions to give more comprehensive information.
Regards.

**Comment by telemachus** [comment]
I appreciate the work. Some of these would make descriptions longer than a single average-sized line in the terminal (circa 80 chars). I usually try to avoid that, but I'll tweak and consider these. Thanks again.

**Comment by telemachus** [comment]
I adjusted a handfull of these, merged and added you to the contributors list.

Thanks again!

**Comment by Yann-R** [comment]
@telemachus Sorry for the too-long texts as one-line descriptions. I really thought I paid attention not to be longer than the longest already existing description that I took as limit length.

Happy to read that you used these contributions. Thanks.

**Comment by telemachus** [comment]
@Yann-R No worries at all. I have to admit that the existing descriptions do not all keep to that rule. But it's something I try to follow wherever possible.

**Pull request merged**
