### PR TITLE
Minor edits to README.md

### PR DESCRIPTION
**Pull request by Zearin**
Numerous small tweaks to formatting and phrasing.

### CODE REVIEW

**Comment by Zearin** [comment]
Forgot to mention: Also added a few sub-headings to make the README more “scannable” when reading.

**Comment by telemachus** [comment]
This looks very good overall. I'm going to pull and check it out shortly. Thanks.

One question though: you seem to have added a lot of extra linebreaks between sections. Any particular reason?

**Comment by Zearin** [comment]
> One question though: you seem to have added a lot of extra linebreaks between sections. Any particular reason?

Since I added a few sub-headings, I added more space between the top-level headings to set them apart visually.  

I did try to keep it minimal, though.  Does it bother you?

**Comment by telemachus** [comment]
> Does it bother you?

Bother is a strong word. :) I usually avoid extra whitespace beyond what is required.
I'll think that part over, but either way will shortly merge the content.

Sorry for the quibble and again thanks for the work.

**Comment by telemachus** [comment]
Pulled. Thanks.

**Pull request merged**
